# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "spkn"
license = "MIT"
licenselink = "https://github.com/stainless/seattleparkour.ninja/blob/master/LICENSE.md"
description = ""
homepage = ""
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "Russell Hay"
  homepage = "http://russellhay.com"
